import 'package:aurora_en/vocab.dart';
import 'package:aurora_en/word.dart';

const vocabData = [
  // Vocab('Vocabulary 1', [
  //   Word('Apple', 'A sweet red or green fruit'),
  //   // Word('Brave', 'Ready to face danger or pain'),
  //   // Word('Cloud', 'A visible mass of water droplets in the sky'),
  //   // Word('Dance', 'Move rhythmically to music'),
  //   // Word('Eagle', 'A large bird of prey with a hooked beak'),
  //   // Word('Flame', 'Hot glowing body of ignited gas'),
  //   // Word('Globe', 'A spherical model of Earth'),
  //   // Word('Honest', 'Truthful and sincere'),
  //   // Word('Island', 'Land surrounded by water'),
  //   // Word('Jolly', 'Happy and cheerful'),
  //   // Word('Kite', 'A toy flown in the wind on a string'),
  //   // Word('Lively', 'Full of energy and enthusiasm'),
  //   // Word('Magnet', 'A piece of iron that attracts other metals'),
  //   // Word('Noble', 'Having high moral qualities'),
  //   // Word('Ocean', 'A vast body of salt water'),
  // ]),
  //
  // Vocab('Vocabulary 2', [
  //   Word('Bear', 'Large heavy mammal with thick fur'),
  //   Word('Calm', 'Peaceful and free from agitation'),
  //   Word('Dream', 'Series of thoughts, images, or emotions during sleep'),
  //   // Word('Earth', 'The third planet from the sun; our home'),
  //   // Word('Forest', 'Large area covered chiefly with trees and undergrowth'),
  //   // Word('Giant', 'Being of great size or strength'),
  //   // Word('Happy', 'Feeling or showing pleasure or contentment'),
  //   // Word('Ice', 'Frozen water, a solid crystalline state'),
  //   // Word('Jewel', 'Precious stone used in ornaments'),
  //   // Word('Kind', 'Friendly, generous, and considerate'),
  //   // Word('Lion', 'Large tawny-colored cat that lives in prides'),
  //   // Word('Moon', 'Natural satellite that orbits Earth'),
  //   // Word('Night', 'Time of darkness between sunset and sunrise'),
  //   // Word('Open', 'Not closed, allowing access or passage'),
  //   // Word('Peace', 'Freedom from disturbance or conflict'),
  // ]),
  // Vocab('Vocabulary 3', [
  //   Word('Quiet', 'Making little or no noise'),
  //   Word('River', 'Large natural flow of water towards a sea or lake'),
  //   Word('Sun', 'Star that provides light and heat to Earth'),
  //   Word('Tree', 'Tall plant with a trunk, branches, and leaves'),
  //   Word('Unity', 'State of being joined as a whole'),
  //   Word('Voice', 'Sound produced by humans using vocal cords'),
  //   Word('Wind', 'Natural movement of air'),
  //   Word('Xray', 'Form of electromagnetic radiation used for imaging'),
  //   Word('Young', 'Having lived for a short time; early in life'),
  //   Word('Zebra', 'African wild horse with black-and-white stripes'),
  //   Word('Animal', 'Multicellular living organism that moves and feeds'),
  //   Word('Bridge', 'Structure built to span a physical obstacle'),
  //   Word('Castle', 'Large fortified building from medieval times'),
  //   Word('Desert', 'Arid region with little rainfall and sparse life'),
  //   Word('Energy', 'Capacity for activity or work'),
  // ]),
  Vocab('Global Citizen', [
    Word(
      'Global Citizen',
      'A person who cares about people, cultures, and the environment around the world.',
      'global_citizen.jpeg',
    ),
    Word(
      'Sustainability',
      'Using natural resources carefully so future generations can enjoy them too.',
      'sustainability.jpeg',
    ),
    Word(
      'Diversity',
      'The presence of many different cultures, people, and ideas together.',
      'diversity.jpeg',
    ),
    Word(
      'Community',
      'A group of people who live, work, or help each other together.',
      'community.jpeg',
    ),
    Word(
      'Conservation',
      'Protecting forests, animals, rivers, and natural resources.',
      'conservation.jpeg',
    ),
    Word(
      'Rainforest',
      'A dense forest with heavy rainfall and rich biodiversity.',
      'rainforest.jpeg',
    ),
    Word(
      'Biodiversity',
      'The variety of plants, animals, and living organisms in one place.',
      'biodiversity.jpeg',
    ),
    Word(
      'Deforestation',
      'The cutting down or destruction of forests.',
      'deforestation.jpeg',
    ),
    Word(
      'Indigenous Peoples',
      'Native communities who have lived in a region for many generations.',
      'indigenous_peoples.jpeg',
    ),
    Word(
      'Amazon River',
      'One of the largest rivers in the world, flowing through the Amazon Rainforest.',
      'amazon_river.jpeg',
    ),
  ]),
  Vocab('Health and Well-being', [
    Word('Health', 'A state of physical and mental well-being.', 'health.jpeg'),
    Word(
      'Well-being',
      'Feeling healthy, happy, and comfortable in daily life.',
      'well_being.jpeg',
    ),
    Word(
      'Exercise',
      'Physical activity that helps keep the body strong and healthy.',
      'exercise.jpeg',
    ),
    Word(
      'Healthy Food',
      'Nutritious food that helps the body grow and stay healthy.',
      'healthy_food.jpeg',
    ),
    Word(
      'Water',
      'An essential drink that keeps the body hydrated and healthy.',
      'water.jpeg',
    ),
    Word('Sleep', 'Resting the body and mind during the night.', 'sleep.jpeg'),
    Word(
      'Doctor',
      'A professional who helps people stay healthy and treats illnesses.',
      'doctor.jpeg',
    ),
    Word(
      'Hospital',
      'A place where sick or injured people receive medical care.',
      'hospital.jpeg',
    ),
    Word(
      'Medicine',
      'A substance used to treat or prevent illness.',
      'medicine.jpeg',
    ),
    Word(
      'Hygiene',
      'Practices that help keep the body clean and healthy.',
      'hygiene.jpeg',
    ),
    Word(
      'Vaccination',
      'A medical treatment that protects people from diseases.',
      'vaccination.jpeg',
    ),
    Word(
      'Disease',
      'An illness that affects the body or mind.',
      'disease.jpeg',
    ),
    Word(
      'Mental Health',
      'Emotional and psychological well-being.',
      'mental_health.jpeg',
    ),
    Word('Safety', 'Being protected from danger or harm.', 'safety.jpeg'),
    Word(
      'Prevention',
      'Actions taken to stop diseases or accidents before they happen.',
      'prevention.jpeg',
    ),
  ]),
];
