import 'package:aurora_en/vocab.dart';
import 'package:aurora_en/word.dart';

const vocabData = [
  Vocab('Vocabulary 1', [
    Word('Apple', 'A sweet red or green fruit'),
    // Word('Brave', 'Ready to face danger or pain'),
    // Word('Cloud', 'A visible mass of water droplets in the sky'),
    // Word('Dance', 'Move rhythmically to music'),
    // Word('Eagle', 'A large bird of prey with a hooked beak'),
    // Word('Flame', 'Hot glowing body of ignited gas'),
    // Word('Globe', 'A spherical model of Earth'),
    // Word('Honest', 'Truthful and sincere'),
    // Word('Island', 'Land surrounded by water'),
    // Word('Jolly', 'Happy and cheerful'),
    // Word('Kite', 'A toy flown in the wind on a string'),
    // Word('Lively', 'Full of energy and enthusiasm'),
    // Word('Magnet', 'A piece of iron that attracts other metals'),
    // Word('Noble', 'Having high moral qualities'),
    // Word('Ocean', 'A vast body of salt water'),
  ]),

  Vocab('Vocabulary 2', [
    Word('Bear', 'Large heavy mammal with thick fur'),
    Word('Calm', 'Peaceful and free from agitation'),
    Word('Dream', 'Series of thoughts, images, or emotions during sleep'),
    // Word('Earth', 'The third planet from the sun; our home'),
    // Word('Forest', 'Large area covered chiefly with trees and undergrowth'),
    // Word('Giant', 'Being of great size or strength'),
    // Word('Happy', 'Feeling or showing pleasure or contentment'),
    // Word('Ice', 'Frozen water, a solid crystalline state'),
    // Word('Jewel', 'Precious stone used in ornaments'),
    // Word('Kind', 'Friendly, generous, and considerate'),
    // Word('Lion', 'Large tawny-colored cat that lives in prides'),
    // Word('Moon', 'Natural satellite that orbits Earth'),
    // Word('Night', 'Time of darkness between sunset and sunrise'),
    // Word('Open', 'Not closed, allowing access or passage'),
    // Word('Peace', 'Freedom from disturbance or conflict'),
  ]),

  Vocab('Vocabulary 3', [
    Word('Quiet', 'Making little or no noise'),
    Word('River', 'Large natural flow of water towards a sea or lake'),
    Word('Sun', 'Star that provides light and heat to Earth'),
    Word('Tree', 'Tall plant with a trunk, branches, and leaves'),
    Word('Unity', 'State of being joined as a whole'),
    Word('Voice', 'Sound produced by humans using vocal cords'),
    Word('Wind', 'Natural movement of air'),
    Word('Xray', 'Form of electromagnetic radiation used for imaging'),
    Word('Young', 'Having lived for a short time; early in life'),
    Word('Zebra', 'African wild horse with black-and-white stripes'),
    Word('Animal', 'Multicellular living organism that moves and feeds'),
    Word('Bridge', 'Structure built to span a physical obstacle'),
    Word('Castle', 'Large fortified building from medieval times'),
    Word('Desert', 'Arid region with little rainfall and sparse life'),
    Word('Energy', 'Capacity for activity or work'),
  ]),

  Vocab('Vocabulary 4', [
    Word('Flower', 'Seed-bearing part of a plant, often colorful and fragrant'),
    Word('Garden', 'Area of ground for growing plants, flowers, or vegetables'),
    Word('Honey', 'Sweet, viscous food substance made by bees'),
    Word('Image', 'Visual representation of something'),
    Word('Jungle', 'Dense tropical forest with tangled vegetation'),
    Word('King', 'Male ruler of a kingdom'),
    Word('Lake', 'Large body of water surrounded by land'),
    Word('Mountain', 'Large natural elevation of the earth’s surface'),
    Word('Nest', 'Structure built by birds to hold eggs and young'),
    Word('Orange', 'Citrus fruit with a tough bright rind and sweet flesh'),
    Word('Pink', 'Pale red color, or a type of flowering plant'),
    Word('Queen', 'Female ruler of a kingdom'),
    Word('Rainbow', 'Arc of spectral colors appearing after rain'),
    Word('Star', 'Luminous astronomical body visible in the night sky'),
    Word('Tiger', 'Large orange-and-black striped big cat'),
  ]),
];
